// Created by iWeb 2.0.4 local-build-20120501

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,194),url:'Genocide_of_the_Herero_%26_Nama_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_1.png'},{rect:new IWRect(3,-3,126,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_2.png'},{rect:new IWRect(129,-3,6,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_3.png'},{rect:new IWRect(129,3,6,194),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_4.png'},{rect:new IWRect(129,197,6,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_5.png'},{rect:new IWRect(3,197,126,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_6.png'},{rect:new IWRect(-3,197,6,6),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_7.png'}],new IWSize(132,200)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_15.png'}],new IWSize(200,150)),stroke_3:new IWEmptyStroke(),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_17.png'},{rect:new IWRect(1,-1,198,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_18.png'},{rect:new IWRect(199,-1,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_19.png'},{rect:new IWRect(199,1,2,148),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_20.png'},{rect:new IWRect(199,149,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_21.png'},{rect:new IWRect(1,149,198,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_22.png'},{rect:new IWRect(-1,149,2,2),url:'Genocide_of_the_Herero_%26_Nama_files/stroke_23.png'}],new IWSize(200,150))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Genocide_of_the_Herero_&_Nama_files/Genocide_of_the_Herero_&_NamaMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id7');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id14');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id16');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id20');applyEffects()}
function onPageUnload()
{Widget.onunload();}
