// Created by iWeb 2.0.4 local-build-20100921

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Films_Dealing_with_Genocide_in_Iraq_files/Films_Dealing_with_Genocide_in_IraqMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');detectBrowser();adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');adjustLineHeightIfTooBig('id35');adjustFontSizeIfTooBig('id35');adjustLineHeightIfTooBig('id37');adjustFontSizeIfTooBig('id37');adjustLineHeightIfTooBig('id39');adjustFontSizeIfTooBig('id39');adjustLineHeightIfTooBig('id41');adjustFontSizeIfTooBig('id41');adjustLineHeightIfTooBig('id42');adjustFontSizeIfTooBig('id42');adjustLineHeightIfTooBig('id43');adjustFontSizeIfTooBig('id43');adjustLineHeightIfTooBig('id44');adjustFontSizeIfTooBig('id44');adjustLineHeightIfTooBig('id45');adjustFontSizeIfTooBig('id45');adjustLineHeightIfTooBig('id46');adjustFontSizeIfTooBig('id46');adjustLineHeightIfTooBig('id47');adjustFontSizeIfTooBig('id47');adjustLineHeightIfTooBig('id48');adjustFontSizeIfTooBig('id48');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id22');fixupIECSS3Opacity('id24');fixupIECSS3Opacity('id26');fixupIECSS3Opacity('id33');fixupIECSS3Opacity('id36');fixupIECSS3Opacity('id38');fixupIECSS3Opacity('id40');applyEffects()}
function onPageUnload()
{Widget.onunload();}
