// Created by iWeb 2.0.4 local-build-20100927

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-5,5,10,200),url:'25_Genocide_in_East_Timor_files/stroke.png'},{rect:new IWRect(-5,-5,10,10),url:'25_Genocide_in_East_Timor_files/stroke_1.png'},{rect:new IWRect(5,-5,385,10),url:'25_Genocide_in_East_Timor_files/stroke_2.png'},{rect:new IWRect(390,-5,10,10),url:'25_Genocide_in_East_Timor_files/stroke_3.png'},{rect:new IWRect(390,5,10,200),url:'25_Genocide_in_East_Timor_files/stroke_4.png'},{rect:new IWRect(390,205,10,10),url:'25_Genocide_in_East_Timor_files/stroke_5.png'},{rect:new IWRect(5,205,385,10),url:'25_Genocide_in_East_Timor_files/stroke_6.png'},{rect:new IWRect(-5,205,10,10),url:'25_Genocide_in_East_Timor_files/stroke_7.png'}],new IWSize(395,210)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,91),url:'25_Genocide_in_East_Timor_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'25_Genocide_in_East_Timor_files/stroke_9.png'},{rect:new IWRect(1,-1,184,2),url:'25_Genocide_in_East_Timor_files/stroke_10.png'},{rect:new IWRect(185,-1,2,2),url:'25_Genocide_in_East_Timor_files/stroke_11.png'},{rect:new IWRect(185,1,2,91),url:'25_Genocide_in_East_Timor_files/stroke_12.png'},{rect:new IWRect(185,92,2,2),url:'25_Genocide_in_East_Timor_files/stroke_13.png'},{rect:new IWRect(1,92,184,2),url:'25_Genocide_in_East_Timor_files/stroke_14.png'},{rect:new IWRect(-1,92,2,2),url:'25_Genocide_in_East_Timor_files/stroke_15.png'}],new IWSize(186,93))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('25_Genocide_in_East_Timor_files/25_Genocide_in_East_TimorMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('../../../../Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
