// Created by iWeb 2.0.4 local-build-20110928

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Films_Dealing_with_the_Haitian_Revolution_files/Films_Dealing_with_the_Haitian_RevolutionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');adjustLineHeightIfTooBig('id36');adjustFontSizeIfTooBig('id36');adjustLineHeightIfTooBig('id37');adjustFontSizeIfTooBig('id37');adjustLineHeightIfTooBig('id38');adjustFontSizeIfTooBig('id38');detectBrowser();adjustLineHeightIfTooBig('id39');adjustFontSizeIfTooBig('id39');Widget.onload();fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id21');fixupIECSS3Opacity('id23');fixupIECSS3Opacity('id25');fixupIECSS3Opacity('id27');fixupIECSS3Opacity('id29');fixupIECSS3Opacity('id31');fixupIECSS3Opacity('id33');fixupIECSS3Opacity('id35');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
