// Created by iWeb 2.0.4 local-build-20100304

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_1:new IWStrokeParts([{rect:new IWRect(-4,4,8,358),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke.png'},{rect:new IWRect(-4,-4,8,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_1.png'},{rect:new IWRect(4,-4,681,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_2.png'},{rect:new IWRect(685,-4,8,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_3.png'},{rect:new IWRect(685,4,8,358),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_4.png'},{rect:new IWRect(685,362,8,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_5.png'},{rect:new IWRect(4,362,681,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_6.png'},{rect:new IWRect(-4,362,8,8),url:'Links_Regarding_the_Intellectual_%26_Ethical_Foundations_of_the_Modern_World_files/stroke_7.png'}],new IWSize(689,366)),stroke_0:new IWEmptyStroke(),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000})});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Links_Regarding_the_Intellectual_&_Ethical_Foundations_of_the_Modern_World_files/Links_Regarding_the_Intellectual_&_Ethical_Foundations_of_the_Modern_WorldMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');detectBrowser();adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
