// Created by iWeb 2.0.4 local-build-20110216

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Genocide_in_Bangladesh_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Genocide_in_Bangladesh_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Genocide_in_Bangladesh_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Genocide_in_Bangladesh_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Genocide_in_Bangladesh_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Genocide_in_Bangladesh_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Genocide_in_Bangladesh_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Genocide_in_Bangladesh_files/stroke_15.png'}],new IWSize(200,150)),stroke_1:new IWStrokeParts([{rect:new IWRect(-3,3,6,194),url:'Genocide_in_Bangladesh_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Genocide_in_Bangladesh_files/stroke_1.png'},{rect:new IWRect(3,-3,150,6),url:'Genocide_in_Bangladesh_files/stroke_2.png'},{rect:new IWRect(153,-3,6,6),url:'Genocide_in_Bangladesh_files/stroke_3.png'},{rect:new IWRect(153,3,6,194),url:'Genocide_in_Bangladesh_files/stroke_4.png'},{rect:new IWRect(153,197,6,6),url:'Genocide_in_Bangladesh_files/stroke_5.png'},{rect:new IWRect(3,197,150,6),url:'Genocide_in_Bangladesh_files/stroke_6.png'},{rect:new IWRect(-3,197,6,6),url:'Genocide_in_Bangladesh_files/stroke_7.png'}],new IWSize(156,200)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Genocide_in_Bangladesh_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Genocide_in_Bangladesh_files/stroke_17.png'},{rect:new IWRect(1,-1,198,2),url:'Genocide_in_Bangladesh_files/stroke_18.png'},{rect:new IWRect(199,-1,2,2),url:'Genocide_in_Bangladesh_files/stroke_19.png'},{rect:new IWRect(199,1,2,148),url:'Genocide_in_Bangladesh_files/stroke_20.png'},{rect:new IWRect(199,149,2,2),url:'Genocide_in_Bangladesh_files/stroke_21.png'},{rect:new IWRect(1,149,198,2),url:'Genocide_in_Bangladesh_files/stroke_22.png'},{rect:new IWRect(-1,149,2,2),url:'Genocide_in_Bangladesh_files/stroke_23.png'}],new IWSize(200,150)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Genocide_in_Bangladesh_files/Genocide_in_BangladeshMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');detectBrowser();adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id16');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id20');applyEffects()}
function onPageUnload()
{Widget.onunload();}
