// Created by iWeb 2.0.4 local-build-20110918

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,162),url:'Atlantic_Revolutions_files/stroke_16.png'},{rect:new IWRect(-3,-3,6,6),url:'Atlantic_Revolutions_files/stroke_17.png'},{rect:new IWRect(3,-3,218,6),url:'Atlantic_Revolutions_files/stroke_18.png'},{rect:new IWRect(221,-3,6,6),url:'Atlantic_Revolutions_files/stroke_19.png'},{rect:new IWRect(221,3,6,162),url:'Atlantic_Revolutions_files/stroke_20.png'},{rect:new IWRect(221,165,6,6),url:'Atlantic_Revolutions_files/stroke_21.png'},{rect:new IWRect(3,165,218,6),url:'Atlantic_Revolutions_files/stroke_22.png'},{rect:new IWRect(-3,165,6,6),url:'Atlantic_Revolutions_files/stroke_23.png'}],new IWSize(224,168)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Atlantic_Revolutions_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Atlantic_Revolutions_files/stroke_1.png'},{rect:new IWRect(1,-1,198,2),url:'Atlantic_Revolutions_files/stroke_2.png'},{rect:new IWRect(199,-1,2,2),url:'Atlantic_Revolutions_files/stroke_3.png'},{rect:new IWRect(199,1,2,148),url:'Atlantic_Revolutions_files/stroke_4.png'},{rect:new IWRect(199,149,2,2),url:'Atlantic_Revolutions_files/stroke_5.png'},{rect:new IWRect(1,149,198,2),url:'Atlantic_Revolutions_files/stroke_6.png'},{rect:new IWRect(-1,149,2,2),url:'Atlantic_Revolutions_files/stroke_7.png'}],new IWSize(200,150)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Atlantic_Revolutions_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Atlantic_Revolutions_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Atlantic_Revolutions_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Atlantic_Revolutions_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Atlantic_Revolutions_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Atlantic_Revolutions_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Atlantic_Revolutions_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Atlantic_Revolutions_files/stroke_15.png'}],new IWSize(200,150)),stroke_3:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Atlantic_Revolutions_files/Atlantic_RevolutionsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');detectBrowser();adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id22');fixupIECSS3Opacity('id23');fixupIECSS3Opacity('id24');fixupIECSS3Opacity('id25');fixupIECSS3Opacity('id26');fixupIECSS3Opacity('id27');fixupIECSS3Opacity('id28');fixupIECSS3Opacity('id29');applyEffects()}
function onPageUnload()
{Widget.onunload();}
