// Created by iWeb 2.0.4 local-build-20100306

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-4,4,8,89),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_8.png'},{rect:new IWRect(-4,-4,8,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_9.png'},{rect:new IWRect(4,-4,681,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_10.png'},{rect:new IWRect(685,-4,8,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_11.png'},{rect:new IWRect(685,4,8,89),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_12.png'},{rect:new IWRect(685,93,8,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_13.png'},{rect:new IWRect(4,93,681,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_14.png'},{rect:new IWRect(-4,93,8,8),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_15.png'}],new IWSize(689,97)),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_1.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_2.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_3.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_4.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_5.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_6.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/stroke_7.png'}],new IWSize(143,268))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Bibliography_of_Analyses_of_the_Rwandan_Genocide_files/Bibliography_of_Analyses_of_the_Rwandan_GenocideMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');detectBrowser();adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
