// Created by iWeb 2.0.4 local-build-20100305

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_0:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-4,4,8,293),url:'Films_Dealing_with_the_Interwar_Period_files/stroke.png'},{rect:new IWRect(-4,-4,8,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_1.png'},{rect:new IWRect(4,-4,681,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_2.png'},{rect:new IWRect(685,-4,8,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_3.png'},{rect:new IWRect(685,4,8,293),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_4.png'},{rect:new IWRect(685,297,8,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_5.png'},{rect:new IWRect(4,297,681,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_6.png'},{rect:new IWRect(-4,297,8,8),url:'Films_Dealing_with_the_Interwar_Period_files/stroke_7.png'}],new IWSize(689,301))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Films_Dealing_with_the_Interwar_Period_files/Films_Dealing_with_the_Interwar_PeriodMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');detectBrowser();adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');Widget.onload();fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
