// Created by iWeb 2.0.4 local-build-20100610

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Cambodian_Genocide_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Cambodian_Genocide_files/stroke_17.png'},{rect:new IWRect(1,-1,198,2),url:'Cambodian_Genocide_files/stroke_18.png'},{rect:new IWRect(199,-1,2,2),url:'Cambodian_Genocide_files/stroke_19.png'},{rect:new IWRect(199,1,2,148),url:'Cambodian_Genocide_files/stroke_20.png'},{rect:new IWRect(199,149,2,2),url:'Cambodian_Genocide_files/stroke_21.png'},{rect:new IWRect(1,149,198,2),url:'Cambodian_Genocide_files/stroke_22.png'},{rect:new IWRect(-1,149,2,2),url:'Cambodian_Genocide_files/stroke_23.png'}],new IWSize(200,150)),stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,194),url:'Cambodian_Genocide_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Cambodian_Genocide_files/stroke_1.png'},{rect:new IWRect(3,-3,261,6),url:'Cambodian_Genocide_files/stroke_2.png'},{rect:new IWRect(264,-3,6,6),url:'Cambodian_Genocide_files/stroke_3.png'},{rect:new IWRect(264,3,6,194),url:'Cambodian_Genocide_files/stroke_4.png'},{rect:new IWRect(264,197,6,6),url:'Cambodian_Genocide_files/stroke_5.png'},{rect:new IWRect(3,197,261,6),url:'Cambodian_Genocide_files/stroke_6.png'},{rect:new IWRect(-3,197,6,6),url:'Cambodian_Genocide_files/stroke_7.png'}],new IWSize(267,200)),stroke_5:new IWEmptyStroke(),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Cambodian_Genocide_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Cambodian_Genocide_files/stroke_25.png'},{rect:new IWRect(1,-1,198,2),url:'Cambodian_Genocide_files/stroke_26.png'},{rect:new IWRect(199,-1,2,2),url:'Cambodian_Genocide_files/stroke_27.png'},{rect:new IWRect(199,1,2,148),url:'Cambodian_Genocide_files/stroke_28.png'},{rect:new IWRect(199,149,2,2),url:'Cambodian_Genocide_files/stroke_29.png'},{rect:new IWRect(1,149,198,2),url:'Cambodian_Genocide_files/stroke_30.png'},{rect:new IWRect(-1,149,2,2),url:'Cambodian_Genocide_files/stroke_31.png'}],new IWSize(200,150)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Cambodian_Genocide_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Cambodian_Genocide_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Cambodian_Genocide_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Cambodian_Genocide_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Cambodian_Genocide_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Cambodian_Genocide_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Cambodian_Genocide_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Cambodian_Genocide_files/stroke_15.png'}],new IWSize(200,150)),stroke_4:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Cambodian_Genocide_files/Cambodian_GenocideMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');detectBrowser();Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id9');applyEffects()}
function onPageUnload()
{Widget.onunload();}
