// Created by iWeb 2.0.4 local-build-20120506

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,194),url:'Cambodian_Genocide_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Cambodian_Genocide_files/stroke_1.png'},{rect:new IWRect(3,-3,261,6),url:'Cambodian_Genocide_files/stroke_2.png'},{rect:new IWRect(264,-3,6,6),url:'Cambodian_Genocide_files/stroke_3.png'},{rect:new IWRect(264,3,6,194),url:'Cambodian_Genocide_files/stroke_4.png'},{rect:new IWRect(264,197,6,6),url:'Cambodian_Genocide_files/stroke_5.png'},{rect:new IWRect(3,197,261,6),url:'Cambodian_Genocide_files/stroke_6.png'},{rect:new IWRect(-3,197,6,6),url:'Cambodian_Genocide_files/stroke_7.png'}],new IWSize(267,200)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Cambodian_Genocide_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Cambodian_Genocide_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Cambodian_Genocide_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Cambodian_Genocide_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Cambodian_Genocide_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Cambodian_Genocide_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Cambodian_Genocide_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Cambodian_Genocide_files/stroke_15.png'}],new IWSize(200,150)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Cambodian_Genocide_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Cambodian_Genocide_files/stroke_17.png'},{rect:new IWRect(1,-1,198,2),url:'Cambodian_Genocide_files/stroke_18.png'},{rect:new IWRect(199,-1,2,2),url:'Cambodian_Genocide_files/stroke_19.png'},{rect:new IWRect(199,1,2,148),url:'Cambodian_Genocide_files/stroke_20.png'},{rect:new IWRect(199,149,2,2),url:'Cambodian_Genocide_files/stroke_21.png'},{rect:new IWRect(1,149,198,2),url:'Cambodian_Genocide_files/stroke_22.png'},{rect:new IWRect(-1,149,2,2),url:'Cambodian_Genocide_files/stroke_23.png'}],new IWSize(200,150)),stroke_1:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Cambodian_Genocide_files/Cambodian_GenocideMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id16');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id20');applyEffects()}
function onPageUnload()
{Widget.onunload();}
