// Created by iWeb 2.0.4 local-build-20100730

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_9.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_10.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_11.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_12.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_13.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_14.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_15.png'}],new IWSize(143,268)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_17.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_18.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_19.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_20.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_21.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_22.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_23.png'}],new IWSize(143,268)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_1.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_2.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_3.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_4.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_5.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_6.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Genocide_%26_Social_Revolution_files/stroke_7.png'}],new IWSize(143,268)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Bibliography_of_Genocide_&_Social_Revolution_files/Bibliography_of_Genocide_&_Social_RevolutionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');detectBrowser();adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
