// Created by iWeb 2.0.4 local-build-20110216

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_9.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_10.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_11.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_12.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_13.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_14.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_15.png'}],new IWSize(143,268)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,266),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_1.png'},{rect:new IWRect(1,-1,141,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_2.png'},{rect:new IWRect(142,-1,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_3.png'},{rect:new IWRect(142,1,2,266),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_4.png'},{rect:new IWRect(142,267,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_5.png'},{rect:new IWRect(1,267,141,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_6.png'},{rect:new IWRect(-1,267,2,2),url:'Bibliography_of_Human_Rights_%26_Women_files/stroke_7.png'}],new IWSize(143,268)),stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Bibliography_of_Human_Rights_&_Women_files/Bibliography_of_Human_Rights_&_WomenMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');detectBrowser();adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
