// Created by iWeb 2.0.4 local-build-20110831

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,123),url:'Hate_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Hate_files/stroke_1.png'},{rect:new IWRect(1,-1,123,2),url:'Hate_files/stroke_2.png'},{rect:new IWRect(124,-1,2,2),url:'Hate_files/stroke_3.png'},{rect:new IWRect(124,1,2,123),url:'Hate_files/stroke_4.png'},{rect:new IWRect(124,124,2,2),url:'Hate_files/stroke_5.png'},{rect:new IWRect(1,124,123,2),url:'Hate_files/stroke_6.png'},{rect:new IWRect(-1,124,2,2),url:'Hate_files/stroke_7.png'}],new IWSize(125,125)),stroke_3:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-4,4,8,133),url:'Hate_files/stroke_8.png'},{rect:new IWRect(-4,-4,8,8),url:'Hate_files/stroke_9.png'},{rect:new IWRect(4,-4,97,8),url:'Hate_files/stroke_10.png'},{rect:new IWRect(101,-4,8,8),url:'Hate_files/stroke_11.png'},{rect:new IWRect(101,4,8,133),url:'Hate_files/stroke_12.png'},{rect:new IWRect(101,137,8,8),url:'Hate_files/stroke_13.png'},{rect:new IWRect(4,137,97,8),url:'Hate_files/stroke_14.png'},{rect:new IWRect(-4,137,8,8),url:'Hate_files/stroke_15.png'}],new IWSize(105,141)),stroke_4:new IWStrokeParts([{rect:new IWRect(-4,4,8,67),url:'Hate_files/stroke_16.png'},{rect:new IWRect(-4,-4,8,8),url:'Hate_files/stroke_17.png'},{rect:new IWRect(4,-4,92,8),url:'Hate_files/stroke_18.png'},{rect:new IWRect(96,-4,8,8),url:'Hate_files/stroke_19.png'},{rect:new IWRect(96,4,8,67),url:'Hate_files/stroke_20.png'},{rect:new IWRect(96,71,8,8),url:'Hate_files/stroke_21.png'},{rect:new IWRect(4,71,92,8),url:'Hate_files/stroke_22.png'},{rect:new IWRect(-4,71,8,8),url:'Hate_files/stroke_23.png'}],new IWSize(100,75)),stroke_5:new IWStrokeParts([{rect:new IWRect(-4,4,8,58),url:'Hate_files/stroke_24.png'},{rect:new IWRect(-4,-4,8,8),url:'Hate_files/stroke_25.png'},{rect:new IWRect(4,-4,92,8),url:'Hate_files/stroke_26.png'},{rect:new IWRect(96,-4,8,8),url:'Hate_files/stroke_27.png'},{rect:new IWRect(96,4,8,58),url:'Hate_files/stroke_28.png'},{rect:new IWRect(96,62,8,8),url:'Hate_files/stroke_29.png'},{rect:new IWRect(4,62,92,8),url:'Hate_files/stroke_30.png'},{rect:new IWRect(-4,62,8,8),url:'Hate_files/stroke_31.png'}],new IWSize(100,66)),stroke_2:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Hate_files/HateMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');detectBrowser();Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id6');IMpreload('Hate_files','shapeimage_5','0');IMpreload('Hate_files','shapeimage_5','1');IMpreload('Hate_files','shapeimage_5','2');fixupIECSS3Opacity('id7');applyEffects()}
function onPageUnload()
{Widget.onunload();}
