// Created by iWeb 2.0.4 local-build-20120420

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Links_Regarding_Ancient_Europe_files/Links_Regarding_Ancient_EuropeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id33');adjustFontSizeIfTooBig('id33');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');adjustLineHeightIfTooBig('id35');adjustFontSizeIfTooBig('id35');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id7');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id36');fixupIECSS3Opacity('id37');fixupIECSS3Opacity('id38');fixupIECSS3Opacity('id39');fixupIECSS3Opacity('id40');fixupIECSS3Opacity('id41');fixupIECSS3Opacity('id42');fixupIECSS3Opacity('id43');fixupIECSS3Opacity('id44');fixupIECSS3Opacity('id45');fixupIECSS3Opacity('id46');fixupIECSS3Opacity('id47');fixupIECSS3Opacity('id48');fixupIECSS3Opacity('id49');applyEffects()}
function onPageUnload()
{Widget.onunload();}
