// Created by iWeb 2.0.4 local-build-20100917

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_3:new IWEmptyStroke(),stroke_14:new IWEmptyStroke(),stroke_5:new IWEmptyStroke(),stroke_2:new IWEmptyStroke(),stroke_7:new IWEmptyStroke(),stroke_4:new IWEmptyStroke(),stroke_9:new IWEmptyStroke(),stroke_8:new IWEmptyStroke(),stroke_0:new IWEmptyStroke(),stroke_11:new IWEmptyStroke(),stroke_12:new IWEmptyStroke(),stroke_13:new IWEmptyStroke(),stroke_10:new IWEmptyStroke(),stroke_1:new IWEmptyStroke(),stroke_6:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Specific_Events_of_Mass_Murder_&_Genocide_files/Specific_Events_of_Mass_Murder_&_GenocideMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');detectBrowser();adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id20');fixupIECSS3Opacity('id21');fixupIECSS3Opacity('id22');fixupIECSS3Opacity('id23');fixupIECSS3Opacity('id24');fixupIECSS3Opacity('id25');fixupIECSS3Opacity('id26');fixupIECSS3Opacity('id27');fixupIECSS3Opacity('id28');fixupIECSS3Opacity('id29');fixupIECSS3Opacity('id30');fixupIECSS3Opacity('id31');applyEffects()}
function onPageUnload()
{Widget.onunload();}
