// Created by iWeb 2.0.4 local-build-20100305

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWEmptyStroke(),shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(4.2426,4.2426),color:'#000000',opacity:0.750000}),stroke_1:new IWStrokeParts([{rect:new IWRect(-4,4,8,293),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke.png'},{rect:new IWRect(-4,-4,8,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_1.png'},{rect:new IWRect(4,-4,681,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_2.png'},{rect:new IWRect(685,-4,8,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_3.png'},{rect:new IWRect(685,4,8,293),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_4.png'},{rect:new IWRect(685,297,8,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_5.png'},{rect:new IWRect(4,297,681,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_6.png'},{rect:new IWRect(-4,297,8,8),url:'Groups,_Sharing_%26_Networking%3A__LinkedIn_files/stroke_7.png'}],new IWSize(689,301))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Groups,_Sharing_&_Networking:__LinkedIn_files/Groups,_Sharing_&_Networking:__LinkedInMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');detectBrowser();adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');Widget.onload();fixupAllIEPNGBGs();applyEffects()}
function onPageUnload()
{Widget.onunload();}
