// Created by iWeb 2.0.4 local-build-20110222

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,215),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_16.png'},{rect:new IWRect(-3,-3,6,6),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_17.png'},{rect:new IWRect(3,-3,329,6),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_18.png'},{rect:new IWRect(332,-3,6,6),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_19.png'},{rect:new IWRect(332,3,6,215),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_20.png'},{rect:new IWRect(332,218,6,7),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_21.png'},{rect:new IWRect(3,218,329,7),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_22.png'},{rect:new IWRect(-3,218,6,7),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_23.png'}],new IWSize(335,221)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_1.png'},{rect:new IWRect(1,-1,198,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_2.png'},{rect:new IWRect(199,-1,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_3.png'},{rect:new IWRect(199,1,2,148),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_4.png'},{rect:new IWRect(199,149,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_5.png'},{rect:new IWRect(1,149,198,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_6.png'},{rect:new IWRect(-1,149,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_7.png'}],new IWSize(200,150)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Ethnic_Cleansing_in_the_Former_Yugoslavia_files/stroke_15.png'}],new IWSize(200,150)),stroke_3:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Ethnic_Cleansing_in_the_Former_Yugoslavia_files/Ethnic_Cleansing_in_the_Former_YugoslaviaMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');detectBrowser();adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id4');fixupIECSS3Opacity('id6');fixupIECSS3Opacity('id8');fixupIECSS3Opacity('id10');fixupIECSS3Opacity('id14');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id16');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id19');fixupIECSS3Opacity('id20');applyEffects()}
function onPageUnload()
{Widget.onunload();}
