// Created by iWeb 2.0.4 local-build-20101103

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWEmptyStroke(),stroke_4:new IWEmptyStroke(),stroke_5:new IWEmptyStroke(),stroke_0:new IWEmptyStroke(),stroke_1:new IWEmptyStroke(),stroke_3:new IWEmptyStroke()});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Films_Dealing_with_the_Genocide_in_Darfur_&_Sudan_files/Films_Dealing_with_the_Genocide_in_Darfur_&_SudanMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id24');adjustFontSizeIfTooBig('id24');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id26');adjustFontSizeIfTooBig('id26');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id28');adjustFontSizeIfTooBig('id28');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id30');adjustFontSizeIfTooBig('id30');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');adjustLineHeightIfTooBig('id32');adjustFontSizeIfTooBig('id32');adjustLineHeightIfTooBig('id33');adjustFontSizeIfTooBig('id33');adjustLineHeightIfTooBig('id34');adjustFontSizeIfTooBig('id34');adjustLineHeightIfTooBig('id35');adjustFontSizeIfTooBig('id35');detectBrowser();adjustLineHeightIfTooBig('id36');adjustFontSizeIfTooBig('id36');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
