// Created by iWeb 2.0.4 local-build-20110818

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-3,3,6,139),url:'Support_files/stroke.png'},{rect:new IWRect(-3,-3,6,6),url:'Support_files/stroke_1.png'},{rect:new IWRect(3,-3,224,6),url:'Support_files/stroke_2.png'},{rect:new IWRect(227,-3,6,6),url:'Support_files/stroke_3.png'},{rect:new IWRect(227,3,6,139),url:'Support_files/stroke_4.png'},{rect:new IWRect(227,142,6,6),url:'Support_files/stroke_5.png'},{rect:new IWRect(3,142,224,6),url:'Support_files/stroke_6.png'},{rect:new IWRect(-3,142,6,6),url:'Support_files/stroke_7.png'}],new IWSize(230,145)),stroke_2:new IWStrokeParts([{rect:new IWRect(-3,3,6,148),url:'Support_files/stroke_16.png'},{rect:new IWRect(-3,-3,6,6),url:'Support_files/stroke_17.png'},{rect:new IWRect(3,-3,110,6),url:'Support_files/stroke_18.png'},{rect:new IWRect(113,-3,6,6),url:'Support_files/stroke_19.png'},{rect:new IWRect(113,3,6,148),url:'Support_files/stroke_20.png'},{rect:new IWRect(113,151,6,6),url:'Support_files/stroke_21.png'},{rect:new IWRect(3,151,110,6),url:'Support_files/stroke_22.png'},{rect:new IWRect(-3,151,6,6),url:'Support_files/stroke_23.png'}],new IWSize(116,154)),stroke_1:new IWStrokeParts([{rect:new IWRect(-3,3,6,87),url:'Support_files/stroke_8.png'},{rect:new IWRect(-3,-3,6,6),url:'Support_files/stroke_9.png'},{rect:new IWRect(3,-3,224,6),url:'Support_files/stroke_10.png'},{rect:new IWRect(227,-3,6,6),url:'Support_files/stroke_11.png'},{rect:new IWRect(227,3,6,87),url:'Support_files/stroke_12.png'},{rect:new IWRect(227,90,6,6),url:'Support_files/stroke_13.png'},{rect:new IWRect(3,90,224,6),url:'Support_files/stroke_14.png'},{rect:new IWRect(-3,90,6,6),url:'Support_files/stroke_15.png'}],new IWSize(230,93))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Support_files/SupportMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');detectBrowser();adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');Widget.onload();fixAllIEPNGs('Media/transparent.gif');IMpreload('Support_files','shapeimage_1','0');IMpreload('Support_files','shapeimage_2','0');IMpreload('Support_files','shapeimage_3','0');IMpreload('Support_files','shapeimage_5','0');IMpreload('Support_files','shapeimage_5','1');IMpreload('Support_files','shapeimage_7','0');IMpreload('Support_files','shapeimage_8','0');IMpreload('Support_files','shapeimage_9','0');IMpreload('Support_files','shapeimage_10','0');applyEffects()}
function onPageUnload()
{Widget.onunload();}
