// Created by iWeb 2.0.4 local-build-20100605

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Communism_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Communism_files/stroke_1.png'},{rect:new IWRect(1,-1,198,2),url:'Communism_files/stroke_2.png'},{rect:new IWRect(199,-1,2,2),url:'Communism_files/stroke_3.png'},{rect:new IWRect(199,1,2,148),url:'Communism_files/stroke_4.png'},{rect:new IWRect(199,149,2,2),url:'Communism_files/stroke_5.png'},{rect:new IWRect(1,149,198,2),url:'Communism_files/stroke_6.png'},{rect:new IWRect(-1,149,2,2),url:'Communism_files/stroke_7.png'}],new IWSize(200,150)),stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Communism_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Communism_files/stroke_17.png'},{rect:new IWRect(1,-1,198,2),url:'Communism_files/stroke_18.png'},{rect:new IWRect(199,-1,2,2),url:'Communism_files/stroke_19.png'},{rect:new IWRect(199,1,2,148),url:'Communism_files/stroke_20.png'},{rect:new IWRect(199,149,2,2),url:'Communism_files/stroke_21.png'},{rect:new IWRect(1,149,198,2),url:'Communism_files/stroke_22.png'},{rect:new IWRect(-1,149,2,2),url:'Communism_files/stroke_23.png'}],new IWSize(200,150)),stroke_5:new IWStrokeParts([{rect:new IWRect(-3,3,6,144),url:'Communism_files/stroke_24.png'},{rect:new IWRect(-3,-3,6,6),url:'Communism_files/stroke_25.png'},{rect:new IWRect(3,-3,144,6),url:'Communism_files/stroke_26.png'},{rect:new IWRect(147,-3,6,6),url:'Communism_files/stroke_27.png'},{rect:new IWRect(147,3,6,144),url:'Communism_files/stroke_28.png'},{rect:new IWRect(147,147,6,6),url:'Communism_files/stroke_29.png'},{rect:new IWRect(3,147,144,6),url:'Communism_files/stroke_30.png'},{rect:new IWRect(-3,147,6,6),url:'Communism_files/stroke_31.png'}],new IWSize(150,150)),stroke_3:new IWEmptyStroke(),stroke_6:new IWEmptyStroke(),stroke_4:new IWEmptyStroke(),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,148),url:'Communism_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Communism_files/stroke_9.png'},{rect:new IWRect(1,-1,198,2),url:'Communism_files/stroke_10.png'},{rect:new IWRect(199,-1,2,2),url:'Communism_files/stroke_11.png'},{rect:new IWRect(199,1,2,148),url:'Communism_files/stroke_12.png'},{rect:new IWRect(199,149,2,2),url:'Communism_files/stroke_13.png'},{rect:new IWRect(1,149,198,2),url:'Communism_files/stroke_14.png'},{rect:new IWRect(-1,149,2,2),url:'Communism_files/stroke_15.png'}],new IWSize(200,150))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Communism_files/CommunismMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');detectBrowser();adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id22');adjustFontSizeIfTooBig('id22');Widget.onload();fixAllIEPNGs('Media/transparent.gif');fixupIECSS3Opacity('id3');fixupIECSS3Opacity('id5');fixupIECSS3Opacity('id7');fixupIECSS3Opacity('id9');fixupIECSS3Opacity('id11');fixupIECSS3Opacity('id13');fixupIECSS3Opacity('id15');fixupIECSS3Opacity('id17');fixupIECSS3Opacity('id18');fixupIECSS3Opacity('id20');fixupIECSS3Opacity('id21');fixupIECSS3Opacity('id23');applyEffects()}
function onPageUnload()
{Widget.onunload();}
